### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Vex1245** [cryptolok/GhostInTheNet#10]
I followed all the steps and got this error

![SmartSelect_20220224-203919_Termux.jpg](https://user-images.githubusercontent.com/100336819/155637363-df9fedd7-7f18-4e56-a9c9-29b84e2ea3de.jpg)

Please help

**Comment by cryptolok** [comment]
1 - why would you name your machine "localhost"?
2 - are you sure about your interface name eth0 ?
3 - do you have sudo rights ?

**Comment by Vex1245** [comment]
> 1 - why would you name your machine "localhost"?
> 2 - are you sure about your interface name eth0 ?
> 3 - do you have sudo rights ?

Im using fakeroot to give my termux access to root files that's why it's called "localhost". Im not sure how to change it, im still very new and learning 

I checked my interface for my wifi and tried wlan0 and still didn't work

How can i get sudo rights ?

[Again im very new to using termux/Linux overall 😅 thank you in advance for taking the time to help 😁 👍]
