### ISSUE TITLE
Network Manager WiFi APs not listed if disconnected manually

### ISSUE THREAD

**Issue by cegi** [cryptolok/GhostInTheNet#4]
I don't know if it comes from the update you added which change the hostname (thanks for that, it's great), but when using Ghost, i have internet connection and my hostname and MAC adress are different, but when clicking on Network-Manager(Mate DE) i don't see any AP anymore, i have to reboot my computer.

I usually use wicd-curses, but after a recent python update it crashes so i'm avoiding it. Is there a work around ? I don't know which manager works best with GhostIntheNet, but wicd-curses worked very fast and fine with it.

**Comment by cryptolok** [comment]
Oh, that's interesting to know ...
Could you please confirm that the cause is really my update by reverting the commit? or simply delete the "hostname" lines in the script.
If that's the case, then I'll debug the hostname generation/changing algorithm.
If it isn't, then try to debug the network/cli (as root) : 
`/etc/init.d/network-manager restart`
if not helping : 
`/etc/init.d/network-manager stop`
`ifconfig wlan0 down`
`rfkill unblock wlan`
`nmcli radio wifi on`
`ifconfig wlan0 up`
`/etc/init.d/network-manager start`
Myself, I use console to manage my networks :)

**Comment by cegi** [comment]
Thanks, yes launching the first command debugged it, and Wifi AP showed up. I removed the lines with hostname, and it works fine. With the new Ghost however network-manager does not show AP anymore, only wired connections,but when i use a CLI network-manager (wicd-curses) i have no problem with Wifi AP, and Ghost act very quickly, so it might just be a problem between Ghost and network-manager. 

Also yesterday there was a big debian update, in which i saw a network-manager modification so maybe not your update on Ghost that is causing it but the network-manager update ? And i'm sure it's after that debian update the problem started to show up when using Ghost.

**Comment by cryptolok** [comment]
So, the problem was the hostname change, but restart of NM (Network Manager) solved it?
If that's it, I'll just add that command to the script :) but can you confirm please, that turning off Ghost doesn't affect the NM?

**Comment by cegi** [comment]
No i did not choose my words correctly, restarting network-manager fixed it until i launched Ghost again, then it happened once more, but as i said it works flawlessly with CLI NM, so it's probably not coming from your script but rather a NM issue. I think you can close the issue as there's not much you can do, i will wait that network-manager get fixed. Thanks for the help

**Comment by cryptolok** [comment]
Actually, I sugested to restart/debug NM just after launching Ghost, in order to try to fix it.
So, can you try those commands after launching Ghost?

**Comment by cegi** [comment]
Here's what i did just now : 

Connected on wifi AP on wlan0 with network-manager of Mate DE
launched "sudo GhostInTheNet on wlan0" in terminal
I had internet connection, different hostname and MAC adress, i saw all my ethernet and WIfi AP
launched "sudo GhostInTheNet off wlan0" in terminal
disconnected from the WIfi AP, and then i didn't see any Wifi AP or Ethernet, and using "/etc/init.d/network-manager restart" fixed it, but i have to launch it each time i want to reconnect.

**Comment by cryptolok** [comment]
OK
I just updated the script, tell me if it's OK for you?

**Comment by cegi** [comment]
Restarted my computer to reset everything, connected to Wifi AP with wlan0, ran "sudo GhostInTheNet on wlan0" in terminal, and the new command you added makes it that i don't have internet connection and don't see any AP. It's obviously an issue with network-manager.

**Comment by cryptolok** [comment]
I updated once again, it should do the trick?

**Comment by cegi** [comment]
No i get : New hostname : 4166
Reinitializing network interface ...
If not connected or taking too long - reconnect manually

[ ok ] Starting network-manager (via systemctl): network-manager.service.

But i can't choose any network to reconnect manually, because i can't see any network anymore.

**Comment by cryptolok** [comment]
OK, I added some stuff, now?

**Comment by cegi** [comment]
Now it worked, i had internet connection, and could see the network AP, but after disconnecting i can't see any AP, i have to run "systemctl restart network-manager".

**Comment by cryptolok** [comment]
Well, at least one good thing so far :)
When you say "disconnectiong", you mean disconnectiong the network or turning off Ghost?

**Comment by cegi** [comment]
When i disconnect directly from network-manager, if i turn off Ghost, i can still see my available network. It only happen when disconnect from NM.

Also very nice news and thanks for that, with the new modification you made, the MAC adress change is persistent after being disconnected using Network-manager (Mate), while before you update it, my MAC would go back to the permanent one if disconnected/switching AP, so i would usually use CLI NM instead because the MAC was persistent, but now i can use network-manager again. Just have to fix this little issue with AP not showing up.

**Comment by cryptolok** [comment]
Well, if you manually disconnect from NM, then I afraid there is not much I can do :)
Perhaps it's just the NM's update, anyway I'll keep open the issue for now.
Thanks for contribution :)

**Comment by cegi** [comment]
Exactly, it's coming from NM for sure. But now MAC adress is persistent so it got even better, thanks for the help. will tell you if in next updates something change.

**Comment by cegi** [comment]
I were wrong, using Ghost 10mn ago i could see the Wifi AP thanks to the commands you added, but when i used "sudo GhostInTheNet off wlan0", i got disconnected and could not see the AP on NM, but still saw them on CLI NM. Just wanted to let you know that disabling Ghost or disconnecting directly from NM make that happen.

EDIT : Any changes made to the connection while being connected with network-manager will make it crashes, so i troubled you for nothing, i think you can revert the change on the Ghost script as it doesn't come from it.

**Comment by cryptolok** [comment]
OK, but I'd prefer to keep the patch though. Perhaps you just need to wait a little in order NM can figure out the network change, but it's still confusing for me :) try maybe:
`/etc/init.d/networking restart`

**Comment by cegi** [comment]
No it doesn't work. I know it's confusing since there is no screenshot, here's how i make it work.

I launch Ghost on wlan0, then connect on Wifi AP.
I disconnect or "Ghost off", get disconnected and can't see AP anymore, so i use "systemctl restart network-manager" and the WIfi APs show up after 5 seconds.

Though if i'm already connected on Wifi, and launch Ghost on wlan0, i'm disconnected, can't see any AP and get on Ghost : **New hostname : 11851
Reinitializing network interface ...
If not connected or taking too long - reconnect manually**

So i need to be disconnected before using Ghost, since it disconnect me and reconnect me, it makes NM crash.

You're right, it's not really annoying i will just wait.

**Comment by cryptolok** [comment]
Well, that's strange since I stop&start the NM in the script and wait 5s to perform DHCP.
I added some lines for NM to be less buggy, perhaps that would help.

**Comment by cegi** [comment]
No it still doesn't work. I'm on Mate DE maybe it's different from you.

**Comment by cryptolok** [comment]
Me I have no graphical environment :) except for browser, only console, only hardcore :)

**Comment by cegi** [comment]
That's very good for resources, but if you have a good computer why limit yourself to console only ? There are many good tools that are only available as Interface, plus it's most of time way easier, so you put more of your time in things you want to do and let the Interface do the rest. Not Hardcore that's for sure, but to each his own value of time.

**Comment by cryptolok** [comment]
I have many VMs and only quad-thread CPU without a GPU, but I upgraded to 16Gb RAM :)
For me it's just philosophical, I do have graphical environment and I launch it when needed (like Firefox) and yes, sometimes I use GUI tools, but for me it's much more quick and flexible to use console if I want to do something, thus almost all my personal tools are console-based :)
But now I do realize that I also have to take in count graphical environments if I publish what I do ...

**Comment by cegi** [comment]
Problem got fixed in a recent patch. Now Wifi APs shows up and MAC change is persistent after being disconnected thanks for the change.

**Comment by cryptolok** [comment]
so, it was NM after all? alright, thanks for contribution any way :) but I'll still remove some changes I made.
